export { default as SocialIcon } from './SocialIcon'
export { default as LinkedlnIcon } from './LinkedlnIcon'
export { default as InstagramIcon } from './InstagramIcon'
export { default as FacebookIcon } from './FacebookIcon'
export { default as TwitterIcon } from './TwitterIcon'
export { default as DotIcon } from './DotIcon'